### ISSUE TITLE
Handle status "disabled" from Jasmine specDone() method

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo-js#33] opened 2016-09-30 22:18 UTC
When just running one spec or a collection of specs using xit or xdescribe, Jasmine calls specDone for all other specs as well, passing the status `disabled`. This status is currently not handled by scenarioo-js and results in a an error:

```
[23:38:00] E/launcher - Cannot read property 'toUpperCase' of undefined
[23:38:00] E/launcher - TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.useCaseEnded (D:\Code\Neo_Git\Source\UI\Neo.UI.Workbench\node_modules\scenarioo-js\lib\scenariooReporter.j
s:163:37)
    at Object.suiteDone (D:\Code\Neo_Git\Source\UI\Neo.UI.Workbench\node_modules\scenarioo-js\lib\reporters\jasmine.js:1
20:33)
    at dispatch (D:\Code\Neo_Git\Source\UI\Neo.UI.Workbench\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2042:2
8)
    at ReportDispatcher.suiteDone (D:\Code\Neo_Git\Source\UI\Neo.UI.Workbench\node_modules\jasmine-core\lib\jasmine-core
\jasmine.js:2013:11)
    at j$.TreeProcessor.nodeComplete (D:\Code\Neo_Git\Source\UI\Neo.UI.Workbench\node_modules\jasmine-core\lib\jasmine-c
ore\jasmine.js:759:20)
    at [object Object].queueRunnerFactory.onComplete [as _onTimeout] (D:\Code\Neo_Git\Source\UI\Neo.UI.Workbench\node_mo
dules\jasmine-core\lib\jasmine-core\jasmine.js:2566:17)
    at Timer.listOnTimeout (timers.js:92:15)
[23:38:00] E/launcher - Process exited with error code 199
```

Jasmine seems to have these states:

* passed
* failed
* pending
* disabled -> only one not handled by scenarioo-js

Versions used are the latest as of now:
* "jasmine-core": "^2.5.2"
* "protractor": "^4.0.9"

Proposal: Handle "disabled" as a separate state in the scenarioEnded() and useCaseEnded() methods in scenariooReporter.js and add a separate counter `disabledScenarios` to the use case store object.

@dola @bruderol What do you think about this proposal? The issue is quite annoying. I wonder why we never ran into it before though... maybe Jasmine changed its behavior in a recent version. It should be very easy to fix. Would be great to include this in the 2.2 release if you agree with the change.

**Comment by bruderol** [comment] 2016-10-03 18:28
Very annoying, I agree. I think I also had this issue once, but didn't find time to dig deeper about it yet,  because this has no priority for us (xit and xdescribe are considered harmful anyway and we do not allow to commit those in my project with a git pre commit hook).

I also think that they changed that recently (I had this problem only, when using protractor 4.x, with 3.x that was no issue, seemed to me it has to do with protractor and not with jasmine somehow ??)

Great that you could find the source of the problem!

What not convinces me yet: Why should we track disabled scenarios and usecases at all? Scenarioo proposes to use `pending` to put tests to be ignored (and tracked!), all disabled tests should not be listed in the scenarioo docu at all in my oppinion and I do not see why whe should track that at all.

Any disagree on that?

**Comment by bruderol** [comment] 2016-10-08 15:07
Ok, I could reproduce the problem and I am working on a solution (not yet sure, what is the best, will let you know here, after some investigation)

**Comment by bruderol** [comment] 2016-10-08 15:42
Ok, If ixed the bug you reported, but now I am running again into another problem, whish is the one I mentioned above, that I once saw in my project. Both problems are rleated to the fact that jasmine and protractor both changed their behaviour slightly, and it seems it calls afterEach now even for disabled/pending tests, which leads to errors in scenarioo and the error output is not really helpful .... will try to fix that other bug too ... still working on it ...

**Comment by bruderol** [comment] 2016-10-08 19:49
the funny thing is, that there seems to be no way to distinguish in the reporter between a suite that was disabled and another suite :-1: only possibility is indeed to count the disabled specs inside and then treat a suite that has only disabled specs as disabled as well (that's how I started to fix it now).

Only problem: no way to distinguish between empty focused suite and an empty disabled suite obviously! :-(

But ok, at least it is not failing anymore now, and empty suites will just be reported as SUCCESS in any case, even if they have not been focused really.

**Comment by bruderol** [comment] 2016-10-08 19:51
@adiherzog what you think about this fix, can you live with that? better idea? only downside I see: empty use cases will allways be reported as SUCCESS even if they were not really selected as focused.

**Comment by bruderol** [comment] 2016-10-08 20:08
consider this as done, fixed on release branch

**Closed by bruderol** 2016-10-08 20:08 UTC
Labels: 3 - Done, bug, v2.2

**Comment by adiherzog** [comment] 2016-10-12 20:10
@bruderol I think reporting empty use cases as SUCCESS is a good solution. Thanks for fixing the issue!

**Comment by bruderol** [comment] 2016-10-14 09:44
@adiherzog No problem, but could you please also review and accept the Pull Request:
https://github.com/scenarioo/scenarioo-js/pull/36

Or @dola could you please do so?
